//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SevenSeas
{
    using System;
    using System.Collections.Generic;
    
    public partial class adbBusEscort
    {
        public int CruiseID { get; set; }
        public string EscortID { get; set; }
        public long IMEI { get; set; }
    
        public virtual adbCruise adbCruise { get; set; }
        public virtual adbMobilePhone adbMobilePhone { get; set; }
    }
}
