//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SevenSeas
{
    using System;
    using System.Collections.Generic;
    
    public partial class adbBusJourney
    {
        public adbBusJourney()
        {
            this.adbBusCard = new HashSet<adbBusCard>();
        }
    
        public int JourneyID { get; set; }
        public int BusNumber { get; set; }
        public string BusCompany { get; set; }
        public string BusLicenseNum { get; set; }
        public Nullable<int> NumberOfSeats { get; set; }
        public string WheelchairAccess { get; set; }
        public string StartLocation { get; set; }
        public string EndLocation { get; set; }
        public int Escort1 { get; set; }
        public int Escort2 { get; set; }
    
        public virtual ICollection<adbBusCard> adbBusCard { get; set; }
        public virtual adbEmployee adbEmployee { get; set; }
        public virtual adbEmployee adbEmployee1 { get; set; }
    }
}
