//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SevenSeas
{
    using System;
    using System.Collections.Generic;
    
    public partial class adbCruiseRouteSchedule
    {
        public int SequenceID { get; set; }
        public int CruiseID { get; set; }
        public int RouteID { get; set; }
        public int PortID { get; set; }
        public int Rank { get; set; }
        public Nullable<System.DateTime> ArrivalDateTime { get; set; }
    
        public virtual adbCruise adbCruise { get; set; }
        public virtual adbPort adbPort { get; set; }
        public virtual adbRoute adbRoute { get; set; }
    }
}
