//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SevenSeas
{
    using System;
    using System.Collections.Generic;
    
    public partial class adbCruise
    {
        public adbCruise()
        {
            this.adbBusEscort = new HashSet<adbBusEscort>();
            this.adbCruiseRouteSchedule = new HashSet<adbCruiseRouteSchedule>();
            this.adbPassengerCruise = new HashSet<adbPassengerCruise>();
        }
    
        public int CruiseID { get; set; }
        public string Name { get; set; }
        public int Ship { get; set; }
        public int Route { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime ReturnDateTime { get; set; }
    
        public virtual ICollection<adbBusEscort> adbBusEscort { get; set; }
        public virtual adbRoute adbRoute { get; set; }
        public virtual adbShip adbShip { get; set; }
        public virtual ICollection<adbCruiseRouteSchedule> adbCruiseRouteSchedule { get; set; }
        public virtual ICollection<adbPassengerCruise> adbPassengerCruise { get; set; }
    }
}
