//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SevenSeas
{
    using System;
    using System.Collections.Generic;
    
    public partial class adbExcursion
    {
        public adbExcursion()
        {
            this.adbAttraction = new HashSet<adbAttraction>();
            this.adbAttractionBooking = new HashSet<adbAttractionBooking>();
            this.adbBusCard = new HashSet<adbBusCard>();
            this.adbExcursionBooking = new HashSet<adbExcursionBooking>();
            this.adbExcursionReview = new HashSet<adbExcursionReview>();
        }
    
        public int ExcursionID { get; set; }
        public int PortID { get; set; }
        public string Name { get; set; }
        public System.DateTime DateTime { get; set; }
        public string Length { get; set; }
        public int MinPassengers { get; set; }
        public Nullable<int> MaxPassengers { get; set; }
        public Nullable<decimal> AdultPrice { get; set; }
        public Nullable<decimal> ChildPrice { get; set; }
    
        public virtual ICollection<adbAttraction> adbAttraction { get; set; }
        public virtual ICollection<adbAttractionBooking> adbAttractionBooking { get; set; }
        public virtual ICollection<adbBusCard> adbBusCard { get; set; }
        public virtual ICollection<adbExcursionBooking> adbExcursionBooking { get; set; }
        public virtual ICollection<adbExcursionReview> adbExcursionReview { get; set; }
        public virtual adbPort adbPort { get; set; }
    }
}
