//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SevenSeas
{
    using System;
    using System.Collections.Generic;
    
    public partial class adbEmployee
    {
        public adbEmployee()
        {
            this.adbCrew = new HashSet<adbCrew>();
            this.adbFirstAid = new HashSet<adbFirstAid>();
            this.adbBusJourney = new HashSet<adbBusJourney>();
            this.adbBusJourney1 = new HashSet<adbBusJourney>();
        }
    
        public int EmployeeID { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string job { get; set; }
        public System.DateTime start_date { get; set; }
        public System.DateTime dob { get; set; }
        public string phone { get; set; }
        public string street { get; set; }
        public string town { get; set; }
        public string postcode { get; set; }
        public string gender { get; set; }
        public Nullable<decimal> salary { get; set; }
    
        public virtual ICollection<adbCrew> adbCrew { get; set; }
        public virtual ICollection<adbFirstAid> adbFirstAid { get; set; }
        public virtual ICollection<adbBusJourney> adbBusJourney { get; set; }
        public virtual ICollection<adbBusJourney> adbBusJourney1 { get; set; }
    }
}
