//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SevenSeas
{
    using System;
    using System.Collections.Generic;
    
    public partial class adbExcursionBooking
    {
        public int PassengerID { get; set; }
        public int ExcursionID { get; set; }
        public Nullable<decimal> TotalCost { get; set; }
        public Nullable<System.DateTime> TimeBooked { get; set; }
    
        public virtual adbExcursion adbExcursion { get; set; }
        public virtual adbPassenger adbPassenger { get; set; }
    }
}
