//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SevenSeas
{
    using System;
    using System.Collections.Generic;
    
    public partial class adbGuestLecturerGuest
    {
        public int GuestID { get; set; }
        public int LecturerID { get; set; }
        public int PassengerID { get; set; }
    
        public virtual adbGuestLecturer adbGuestLecturer { get; set; }
        public virtual adbPassenger adbPassenger { get; set; }
    }
}
