//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SevenSeas
{
    using System;
    using System.Collections.Generic;
    
    public partial class adbGuestLecturer
    {
        public adbGuestLecturer()
        {
            this.adbGuestLecturerGuest = new HashSet<adbGuestLecturerGuest>();
        }
    
        public int LecturerID { get; set; }
        public int PassengerID { get; set; }
        public string Institute { get; set; }
        public string LectureTopic { get; set; }
    
        public virtual ICollection<adbGuestLecturerGuest> adbGuestLecturerGuest { get; set; }
        public virtual adbPassenger adbPassenger { get; set; }
    }
}
