//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SevenSeas
{
    using System;
    using System.Collections.Generic;
    
    public partial class adbMobilePhone
    {
        public adbMobilePhone()
        {
            this.adbBusEscort = new HashSet<adbBusEscort>();
        }
    
        public long IMEI { get; set; }
        public string Make { get; set; }
        public string Model { get; set; }
        public string PhoneNumber { get; set; }
        public Nullable<int> ShipID { get; set; }
        public Nullable<System.DateTime> IssueDateTime { get; set; }
        public Nullable<System.DateTime> ReturnDateTime { get; set; }
    
        public virtual ICollection<adbBusEscort> adbBusEscort { get; set; }
        public virtual adbShip adbShip { get; set; }
    }
}
