//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SevenSeas
{
    using System;
    using System.Collections.Generic;
    
    public partial class adbPassengerCruise
    {
        public adbPassengerCruise()
        {
            this.adbShipCard = new HashSet<adbShipCard>();
        }
    
        public int CruiseID { get; set; }
        public int PassengerID { get; set; }
        public System.DateTime BookedDate { get; set; }
    
        public virtual adbCruise adbCruise { get; set; }
        public virtual adbPassenger adbPassenger { get; set; }
        public virtual ICollection<adbShipCard> adbShipCard { get; set; }
    }
}
