//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SevenSeas
{
    using System;
    using System.Collections.Generic;
    
    public partial class adbPassenger
    {
        public adbPassenger()
        {
            this.adbAttractionBooking = new HashSet<adbAttractionBooking>();
            this.adbBusCard = new HashSet<adbBusCard>();
            this.adbExcursionBooking = new HashSet<adbExcursionBooking>();
            this.adbExcursionReview = new HashSet<adbExcursionReview>();
            this.adbGuestLecturer = new HashSet<adbGuestLecturer>();
            this.adbGuestLecturerGuest = new HashSet<adbGuestLecturerGuest>();
            this.adbPassengerCruise = new HashSet<adbPassengerCruise>();
        }
    
        public int PassengerID { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string address { get; set; }
        public string city { get; set; }
        public string county { get; set; }
        public string postcode { get; set; }
        public string country { get; set; }
        public string phone { get; set; }
        public string email { get; set; }
        public string gender { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
    
        public virtual ICollection<adbAttractionBooking> adbAttractionBooking { get; set; }
        public virtual ICollection<adbBusCard> adbBusCard { get; set; }
        public virtual ICollection<adbExcursionBooking> adbExcursionBooking { get; set; }
        public virtual ICollection<adbExcursionReview> adbExcursionReview { get; set; }
        public virtual ICollection<adbGuestLecturer> adbGuestLecturer { get; set; }
        public virtual ICollection<adbGuestLecturerGuest> adbGuestLecturerGuest { get; set; }
        public virtual ICollection<adbPassengerCruise> adbPassengerCruise { get; set; }
    }
}
