//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SevenSeas
{
    using System;
    using System.Collections.Generic;
    
    public partial class adbPort
    {
        public adbPort()
        {
            this.adbCruiseRouteSchedule = new HashSet<adbCruiseRouteSchedule>();
            this.adbExcursion = new HashSet<adbExcursion>();
            this.adbRoute = new HashSet<adbRoute>();
            this.adbRoute1 = new HashSet<adbRoute>();
            this.adbTracking = new HashSet<adbTracking>();
            this.adbTracking1 = new HashSet<adbTracking>();
        }
    
        public int PortID { get; set; }
        public string PortName { get; set; }
        public string Location { get; set; }
    
        public virtual ICollection<adbCruiseRouteSchedule> adbCruiseRouteSchedule { get; set; }
        public virtual ICollection<adbExcursion> adbExcursion { get; set; }
        public virtual ICollection<adbRoute> adbRoute { get; set; }
        public virtual ICollection<adbRoute> adbRoute1 { get; set; }
        public virtual ICollection<adbTracking> adbTracking { get; set; }
        public virtual ICollection<adbTracking> adbTracking1 { get; set; }
    }
}
