//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SevenSeas
{
    using System;
    using System.Collections.Generic;
    
    public partial class adbShipCard
    {
        public adbShipCard()
        {
            this.adbTracking = new HashSet<adbTracking>();
        }
    
        public int CardID { get; set; }
        public int PassengerID { get; set; }
        public int CruiseID { get; set; }
        public double AmountDue { get; set; }
    
        public virtual adbPassengerCruise adbPassengerCruise { get; set; }
        public virtual ICollection<adbTracking> adbTracking { get; set; }
    }
}
